<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Phase 11B.1 v11B.1.2 §3 — normalized product_translations table.
 *
 * Per dev §3:
 *   "A resource-specific translation table is also acceptable and may
 *    provide stronger indexing and validation."
 *
 * This table replaces the ad-hoc JSON-column approach for moderated content.
 * The legacy JSON columns (name_translations, short_description_translations,
 * description_translations) REMAIN on the products table for backward
 * compatibility with v11A.5 / v11B.1 / v11B.1.1 callers and the existing
 * search service. The resolver service consults this table FIRST (when an
 * approved row exists), then falls back to the JSON columns, then to the
 * English source.
 *
 * Workflow statuses (per dev §6):
 *   missing         — no translation entered for this field+locale
 *   pending         — translation requested but not yet generated
 *   machine_draft   — auto-generated, requires human review (never public by default)
 *   human_reviewed  — a human checked it but not yet approved
 *   approved        — published; visible on the storefront
 *   rejected        — explicitly rejected; never visible
 *   stale           — was approved, but English source has since changed
 *
 * The source_checksum (SHA-256 of the English source value at translation time)
 * lets the system detect when the source has changed and the translation needs
 * re-approval. This is independent of `updated_at` because we want stable
 * "is the English source the same as when this Arabic was approved" semantics.
 *
 * `source_provenance` records where the translation came from:
 *   manual          — vendor or admin typed it
 *   import          — bulk CSV/XLSX import
 *   machine         — auto-generated by a (future) provider
 *
 * No data is destroyed by this migration. Existing JSON-column translations
 * are migrated by a separate seeder so they receive a proper status row.
 */
return new class extends Migration {

    public function up(): void
    {
        if (Schema::hasTable('product_translations')) {
            return;
        }

        Schema::create('product_translations', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('product_id');
            $table->string('locale', 8);
            $table->string('field', 40);    // name | short_description | description
            $table->text('value')->nullable();

            // Workflow status
            $table->string('status', 24)->default('missing');

            // Where this translation came from
            $table->string('source_provenance', 24)->default('manual');

            // SHA-256 of the English source value AT THE TIME this translation
            // was approved. When the English source changes and its current
            // checksum no longer matches, the translation is marked 'stale'.
            $table->char('source_checksum', 64)->nullable();

            // Audit
            $table->unsignedBigInteger('reviewed_by')->nullable();
            $table->timestamp('translated_at')->nullable();
            $table->timestamp('reviewed_at')->nullable();

            $table->timestamps();

            // Unique resource+locale+field combination — exactly one row per
            // (product, locale, field). UPSERT writes update existing rows.
            $table->unique(['product_id', 'locale', 'field'], 'product_translations_unique');

            // Common lookup: WHERE product_id=? AND locale=? AND status='approved'
            $table->index(['product_id', 'locale', 'status'], 'product_translations_resolve_idx');

            // Admin moderation queue lookup: WHERE status IN (...) ORDER BY translated_at DESC
            $table->index(['status', 'locale'], 'product_translations_status_idx');

            // FKs: cascade delete the translations when the product is deleted.
            // reviewed_by → set null on user deletion so audit history survives.
            $table->foreign('product_id')->references('id')->on('products')->cascadeOnDelete();
            $table->foreign('reviewed_by')->references('id')->on('users')->nullOnDelete();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('product_translations');
    }
};
